Altinn/app-localtest

docker-compose.yml
The legacy `altinn-pdf` doesn't support the new M1/2 processors from Apple. This minor change make it run in compability mode, which is totally fine for this service.
=> fixing alting pdf for m1 processors

README.md
The diff is outdated, and it is better to select the correct level than to hard code it.
=> Changing auth level is just a drop-down

.gitignore
The LocalTest.csproj.user must be ignored by git.
=> Ignore user file generated by Visual Studio

Dockerfile, src/Controllers/HomeController.cs, src/Services/LocalApp/Implementation/LocalAppHttp.cs, src/Services/Register/Implementation/PartiesWrapper.cs, src/Services/TestData/TestDataService.cs
* Use cached layers for Dockerfile to improve repeated build times locally.
* Set longer expiration on the cookie that remembers your preferred user for login (as well as syncing AltinnPartyId)
* Ignore a few nullability warnings to make the build warning free
* I don't have any idea about better error handling than a NullPointerException
so I just ignore with !
=> A few minor fixes

src/Controllers/HomeController.cs, src/Views/Home/Index.cshtml
Add a button to ease the process of changing/refreshing the authentication cookie without starting a new instance of the application.
Button post to the same endpoint but if action is reauthenticate the method returns 204 no content after cookie is updated.
Makes testing of apps where different users with different roles are needed to complete the entire process
=> Add a button to refresh authentication without starting new instance

testdata/Profile/User/1001.json, testdata/Profile/User/1002.json, testdata/Profile/User/1003.json, testdata/Profile/User/12345.json, testdata/Profile/User/1337.json
When the below issue gets fixed, the `doNotPromptForParty` preference will actually have an effect in app-frontend, so I'm setting this to true for the test users so that we don't have to go through party selection every time.
- https://github.com/Altinn/app-frontend-react/issues/268
=> Do not prompt for party preference

src/Controllers/Register/PartiesController.cs
I have removed the Authorize attribute on PartiesController for Register to allow services without a User context to call its actions. In the actual Register component, the "PlatformAccess" policy is applied([link](https://github.com/Altinn/altinn-register/blob/e5b7bfaeecc1e1eaeeb44837d2c3032f79119501/src/Controllers/PartiesController.cs#L22)), indicating that only services should be authorized to call it. Because no PlatformAccessToken is present when testing an app locally, calls to this controller will be unauthorized with 401 status code. Hence why I have removed the attribute.
`Not applicable`
`Not applicable`
`not applicable`
=> Align the authorization policy of PartiesController for Register with the register component authorization policy

src/Services/LocalApp/Implementation/LocalAppFile.cs
Localtest would fail to locate textresources if started with `dotnet run`
=> Fix bug where GetTextResources failed if localtest is started with dotnet run

.vscode/launch.json, .vscode/tasks.json, loadbalancer/templates/nginx.conf.conf, src/Controllers/HomeController.cs
While working on https://github.com/Altinn/app-localtest/issues/59, I discovered a few minor issues, that I think makes sense to review separately from the main code.
* Add vscode debug files
* add support for proxying /_framework/aspnetcore-browser-refresh.js calls through the loadbalancer by rewriting the both the url and the script reference.
* Fix a few C# formatting isuses
-  https://github.com/Altinn/app-localtest/issues/59
=> Various updates to app-localtest

loadbalancer/templates/nginx.conf.conf, src/Configuration/LocalPlatformSettings.cs, src/Controllers/DebugUsersController.cs, src/Controllers/FrontendVersionController.cs, src/Controllers/HomeController.cs, src/Controllers/StorageExplorerController.cs, src/Controllers/TenorUsersController.cs, src/Models/Authentication/CustomClaim.cs, src/Models/Authorization/Role.cs, src/Models/TenorViewModel.cs, src/Services/Tenor/Models/BrregErFr.cs, src/Services/Tenor/Models/Freg.cs, src/Services/Tenor/TenorDataReader.cs, src/Services/TestData/AppTestDataModel.cs, src/Services/TestData/TestDataService.cs, src/Startup.cs, src/Views/FrontendVersion/Index.cshtml, src/Views/Home/Index.cshtml, src/Views/Shared/_Layout.cshtml, src/Views/StorageExplorer/Index.cshtml, src/Views/TenorUsers/Index.cshtml
Now you can open a separate tab on the localtest site and upload tenor
kildedata to localtest internal storage. If there are relevant tenor files
in storage, those will replace Ola Nordmann and Sofie Salt as the localtest
users. You can also select a subset of the files to downoad testData.json
to be used as app local users.
3622.87.84340
In addtition to the user management page, I have included the following changes.
* Cleanup of login page and use the menu on top instead of links scattered all over the login screen
* Use latest bootstrap (from CDN, per getboostrap.com instructions)
* Split HomeController into multiple smaller controllers.
* Move `Reauthenticate` button besides the login button and make it a less visible color.
* Loadbalancer redirects "/" and /Home/* to localtest, so …
=> Add page for uploading json files from tenor to configure persons and orgs

src/Controllers/HomeController.cs
HTTP attributes were missing for actions `GetTestUserToken` and `GetTestOrgToken` making them unusable. This PR annotates the actions with `HttpGet` attribute with a binding to the input parameter so that they can be used again.
=> Add HTTP attributes to actions in HomeController

.env.template, Makefile, README.md, docker-compose.yml, loadbalancer/templates/nginx.conf.conf, podman-compose.yml, scripts/OpenAppPortInHyperVFirewall.ps1, src/Configuration/LocalPlatformSettings.cs, src/Controllers/FrontendVersionController.cs, src/Models/LocalFrontendInfo.cs, src/Services/LocalFrontend/Implementation/LocalFrontendService.cs, src/Services/LocalFrontend/Interface/ILocalFrontendService.cs, src/Startup.cs, src/appsettings.Docker.json, src/appsettings.Podman.json, src/appsettings.json
This started out as a fix for new apple silicone but got bigger as problems in other OSes was discovered.
* Fixed some issues that surfaced when trying to run app-localtest on an Mac-M3 machine.
* Also added some commands to help those running old versions of podman.
* Make localtest work with podman and compose on windows
* Provide a hack for fixing the problem with bind mounts giving permission denied inside containers
=> Bugfix make podman work on fedora, apple silicone and windows OS

Makefile, README.md, podman-compose.yml
=> Podman: Mounting volumes with `z` to work around permission issues

docker-compose.yml, loadbalancer/Dockerfile, loadbalancer/templates/nginx.conf.conf, podman-compose.yml
This adds support for replacing any frontend version in `Index.cshtml`. Unfortunately, this was a bit more involved than expected, since the standard `sub_filter` only allows simple string substitution and not regex. To get around this, I needed the third-party [ngx_http_substitutions_filter_module](https://www.nginx.com/resources/wiki/modules/substitutions/). This required some modifications to the standard docker image for nginx which I based on [this](https://github.com/tofran/nginx-with-substitutions-filter-docker).
This also fixes a bug where it would not find the frontendVersion cookie if it was the last one in the `Cookies` header. This is because it previously required the string to end with a `;`. This probably explains the flakyness I myself have experienced with this before.
- …
=> Support any version in Index.cshtml when replacing frontend version

docker-compose.yml, podman-compose.yml
- This updates browserless to the latest version that works on both x84 and arm. The version in tt02 and prod is slightly newer than this (21.4.1).
- Also adds `hosts.containers.internal` to docker-compose PDF generator so the same local hostname can be used for both podman and docker for local PDF generator testing.
- https://github.com/Altinn/app-lib-dotnet/pull/432
=> Update browserless and add extra_hosts

src/Services/Storage/Implementation/DataRepository.cs, src/Services/Storage/Implementation/DataService.cs
There have been reported issues with the new PATCH endpoint in localtest with error messages like
```
fail: Altinn.App.Api.Controllers.DataController[0]
Unable to update data element 57abc10b-d54d-4fd8-bcee-79876d3feaee for instance 500000/8125c8ac-7624-44f3-8429-37ab780aa86c
Altinn.App.Core.Helpers.PlatformHttpException: 500 - Internal Server Error - System.IO.IOException: The process cannot access the file '/AltinnPlatformLocal/blobs/krt/krt-1185a-1/8125c8ac-7624-44f3-8429-37ab780aa86c/data/57abc10b-d54d-4fd8-bcee-79876d3feaee' because it is being used by another process.
```
This is likely caused by not closing streams.
=> Don't keep file streams open

src/Startup.cs, src/appsettings.Podman.json
I ran into a problem testing an app locally, with localtest running in Podman. The issue is that the endpoint for the openid connect configuration generates a URL to the JWK that the app is unable to reach.
Could I have solved it in a different way? Changing settings in my app?
Configuration in my app points to localhost:5101 for all platform endpoints. These are default settings for a new app and they seems to work. The issue starts when localtest returns a generated URL in a response like for the openid connect configuration.
=> Fixes for app testing with localtest in podman

testdata/Register/Person/01017512345.json, testdata/Register/Person/01039012345.json, testdata/Register/Person/01899699552.json, testdata/Register/Person/08829698278.json, testdata/Register/Person/17858296439.json
This pull request aims to standardize the "MailingAddress" field for local test users to align with the expected format in Altinn tt02 and production environments. Currently, the "MailingAddress" field for local test users consists of the concatenation of the AddressStreetName and AddressHouseNumber fields. 
However, to ensure consistency and minimize discrepancies between environments, it's proposed that the "MailingAddress" for all local test users should be composed of the AddressStreetName, AddressHouseNumber, AddressHouseLetter, MailingPostalCode and MailingPostalCity fields.
This change ensures that the prefill data displayed in the local test environment mirrors that of Altinn tt02 and production environments, thereby preventing unexpected discrepancies and reducing additional work …
=> Refine MailingAddress data for local test users

src/Controllers/Storage/DataController.cs
A better approach would be to wait 1 minute before setting it to clean, and provide some sort of known test file that always is `Infected`, but this simple fix makes it possible to use EnableFileScan locally.
The current code comes from https://github.com/Altinn/app-localtest/pull/46 which does not seem to deliberately force localtest users to not enable filescan.
=> Set FileScanResult to Clean in localtest.

src/LocalTest.csproj, src/Services/Storage/Implementation/InstanceService.cs
Unify specific `altinn-storage` change with implementation in `app-localtest`.
This change is required for an `app-lib-dotnet` patch related to duplicate signatures (PR below). 
✅ Using the test setup [described here](https://github.com/Altinn/app-lib-dotnet/pull/617), it has been confirmed that _existing_ behavior is preserved with the current builds of `app-lib-dotnet` and that _new_ expected behavior is achieved with [the proposed new feature in app-lib-dotnet](https://github.com/Altinn/app-lib-dotnet/pull/617).
- https://github.com/Altinn/altinn-storage/pull/392
- https://github.com/Altinn/altinn-storage/pull/404
- https://github.com/Altinn/app-lib-dotnet/pull/617
=> Pass `SignRequest.GeneratedFromTask` to `DataElementHelper.CreateDataElement`

loadbalancer/templates/nginx.conf.conf
Nginx refused to boot when a hostname was invalid
Letting the upstream be a variable makes Nginx not crash on startup, and it will resolve dynamically
- #97
=> Nginx refused to boot when a hostname was invalid

infra/grafana-dashboards/app.json
Changes to default App grafana dashboard to reflect change in metric name
=> fix: use new metric name for stats

src/Notifications/API/Validators/EmailNotificationOrderRequestValidator.cs, src/Notifications/API/Validators/SmsNotificationOrderRequestValidator.cs, src/Notifications/API/Validators/ValidationConstants.cs
Copied latest changes in notifications
=> latest notifications validation logic

src/Services/Storage/Implementation/InstanceRepository.cs
Make InstanceRepository.GetInstancesFromQuery async and await postProcess function call.
When getting a list of instances of an app, there is an async call to PostProcess, that fills in data-array (among other tings). The GetInstances method did not await this postProcess.
The whole function is made async. The ForEach call is replaced with Select, and wrapped in Task.WhenAll(  ).
The Task wrapper on the returned object is removed.
None. Issue was discussed on Slack channel produkt-altinn-studio
=> Fix GetInstances async postprocess

src/Services/Storage/Implementation/InstanceRepository.cs
[My previous PR](https://github.com/Altinn/app-localtest/pull/110) introduced a NullPointerException for completed instances, which caused GetInstancesByQuery to only return 500 Server error when there are complete instances in the storage. This PR fixes this issue.
Added [null conditional](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-) to the problematic object.
None
=> Fix NullPointerException with completed instances in GetInstancesByQuery.

src/Controllers/Storage/ProcessController.cs
Due to a patch in https://github.com/Altinn/altinn-storage/pull/414, ProcessController treats `FlowType=AbandonCurrentMoveToNext` identically to `FlowType=CompleteCurrentMoveToNext`. This has now proven to be problematic, as described in https://github.com/Altinn/app-lib-dotnet/issues/818.
This PR intercepts `AbandonCurrentMoveToNext` and treats it as `reject` instead of whatever `altinn:taskType` from the current step was.
**NOTE**: This functionality must be implemented in [altinn-storage](https://github.com/Altinn/altinn-storage) as well. This will be the next step, after we have confirmed functionality and reached agreement on how it should look in localtest.
- https://github.com/Altinn/app-lib-dotnet/issues/818
=> Treat `FlowType=AbandonCurrentMoveToNext` as `reject` action

testdata/authorization/partylist/1337.json
In the test-data for parties, Oslo and Bergen has the orgnr. `897069651` and `897069652` respectively, as can be seen here:
But these were switched around in the partylist file for DDG fitness under `childParties`, resulting in an inconsistency depending on if we are checking the party in the currentParty response, or if we are matching the instance owner from the instance data with the list of parties:
- Discovered while looking into https://github.com/Altinn/app-frontend-react/issues/2568
=> Fix inconsistency in sub-units for DDG fitness

.github/workflows/localtest-pr.yml, .vscode/launch.json, Dockerfile, global.json, src/LocalTest.csproj
Update to .NET 8
Tested
* Storage explorer
* Login
* Login with prefill
* Filled in and and completed a basic app as a user
* Changing frontend version
* `GetTestOrgToken`
Have not tested the user admin page, no idea how it works
- #2
=> Update to .NET 8

src/Models/Authentication/DiscoveryDocument.cs
This crashes on the latest version of
Microsoft.IdentityModel.Protocols.OpenIdConnect
And is required for app-lib-dotnet 8.5
Must be merged before
- https://github.com/Altinn/app-lib-dotnet/pull/920/files
=> Fix discovery document to not print `null` for bolean properties

src/Notifications/.editorconfig, src/Services/Register/Implementation/TooManyFailedLookupsException.cs
* Remove obsolete seralization for exception
* Ignore CS8632 for copied code in notifications, because we don't want to modify copied files to have `#nullable enable`.
=> Make Localtest compile without warnings

src/Controllers/HomeController.cs, src/Services/Authentication/Implementation/AuthenticationService.cs, src/Services/Authentication/Interface/IAuthentication.cs
Scopes typically come from the caller, so this enables users to inject their own scopes
- N/A
=> Enable passing scopes to org token

src/Configuration/LocalPlatformSettings.cs, src/Controllers/HomeController.cs, src/Models/TokensModel.cs, src/Services/Authentication/Implementation/AuthenticationService.cs, src/Services/Authentication/Interface/IAuthentication.cs, src/Views/Home/Tokens.cshtml, src/Views/Shared/_Layout.cshtml
I'm tired of answering the question on how to get API tokens in localtest, so now they are available on a separate page.
I did my best to mimic the current design as much as possible.
=> New page for easily finding the Urls for localtest ApiTokens

testdata/Register/Org/043871668.json, testdata/Register/Party/500004.json
For testing the organisation lookup component locally. We do the [mod11 check ](https://www.brreg.no/om-oss/registrene-vare/om-enhetsregisteret/organisasjonsnummeret/) for org numbers to validate. The test data for organisations which already exist in localtest do not pass this test.
=> Chore/ add org test data with valid org nr

src/Controllers/Authorization/RolesController.cs
Adds the get roles endpoint from main as it is needed for this PR:
https://github.com/Altinn/app-lib-dotnet/pull/983
Copy paste of the endpoint from core.
- https://github.com/Altinn/app-frontend-react/issues/2089
=> added roles endpoint from core

src/Services/Authorization/Implementation/ContextHandler.cs
Found this when doing service owner requests with an orgNo that had no party information in localtest (digdirs orgno, pretending to be ttd)
- N/A
=> Null-check party when trying to enrich subject attributes during authz

src/Controllers/TestAuthenticationController.cs, src/Models/Authentication/AuthenticationTypes.cs, src/Services/Authentication/Implementation/TestAuthenticationService.cs, src/Services/Authentication/Interface/IAuthentication.cs, src/Startup.cs
Adds a controller that implements test authentication similar to `TestAuthentication` in app-lib. These have been compared to "real" tokens so that format and encoding is the same. I've added a `actual_iss` claim as a simple way for app-lib to not do the `FromLocaltest` token parsing for these
Depends on https://github.com/Altinn/app-localtest/pull/170
- N/A
=> New test authentication methods

src/Controllers/InfraController.cs, src/Views/Shared/_Layout.cshtml
The index page polls `/Home/Infra/Grafana` to check if Grafan is running. This check returns a 503 error if it is unable to connect to Grafana, which in itself makes sense, but is causing Cypress tests to fail when running locally.
As a compromise/solution, this PR simply returns 204 when we have determined that the service is not running -- and alters the consumer slightly to look for 200 specifically instead of "all OK replies" from the infra controller.
=> Fixes issue with Grafana vs. local Cypress testing
