Altinn/app-localtest

README.md
=> Corrected a bug in the readme

src/Services/Authorization/Implementation/PolicyRetrievalPoint.cs
Missing dollar sign prevented authorization from actually going through
=> added missing dollar sign for authorization

.gitignore, src/Constants/Authorization/XacmlRequestAttribute.cs, src/Models/Authorization/XacmlResourceAttributes.cs, src/Services/Authorization/Implementation/ContextHandler.cs
Updated context handler to match production
=> Matching authorization

testdata/authorization/partylist/1001.json, testdata/authorization/partylist/1002.json, testdata/authorization/roles/User_1001/party_500000/roles.json, testdata/authorization/roles/User_1002/party_500000/roles.json, testdata/authorization/roles/User_1337/party_500000/roles.json
Added some roles for Pengelens Partner and Gjentagende forelder to DDG Fitness in order to test the signing flow where different users have access to different steps in the process. Pengelens partner is "daglig leder" and Gjentagende forelder is the auditor.
https://dev.altinn.studio/repos/ttd/signing-test
=> Testdata: Added roles for testing signing

docker-compose.yml
This is out in production, so it's anticipated that people will need this service to test their new PDFs very soon.
=> Starting new PDF service as default

README.md
=> Clarify that /App is a folder in your application

README.md
Setup step 2: Moved code to the top.
Setup step 3: Specified that you must have created and cloned an app to perform this step. Also example of changing into the `App` directory.
=> Updated Setup steps 2 and 3

README.md
Starting an application in LocalTest requires that a data model has been added to the application. 
This requirement has been included in the "Start your app" step with a link to data modelling in Altinn.
=> Included 'added datamodel' as prerequisite to start app in LocalTest

src/Services/Storage/Implementation/DataService.cs
Updated to reflect latest bugfix in storage
=> updated logic for generating sha256 hash

src/Controllers/Storage/DataController.cs, src/Helpers/Storage/DataElementHelper.cs, src/LocalTest.csproj
Replicate logic from PR https://github.com/Altinn/altinn-storage/pull/232
=> Replicate logic from storage

src/Controllers/Storage/ProcessController.cs, src/Services/Storage/Implementation/ApplicationService.cs, src/Services/Storage/Implementation/InstanceService.cs, src/Services/Storage/Interface/IApplicationService.cs
=> Replicate process controller logic in storage

src/Controllers/Storage/DataController.cs
Localtest implementation of https://github.com/Altinn/altinn-storage/issues/253
- https://github.com/Altinn/altinn-storage/issues/253
=> Implement similar 0bytes logic in localtest as in altinn-storage

testdata/Profile/User/1001.json
=> fix testdata Pengelens Partner phone number

src/Controllers/Storage/InstancesController.cs, src/Helpers/Storage/AuthorizationHelper.cs, src/LocalTest.csproj, src/Services/Storage/Implementation/AuthorizationService.cs, src/Services/Storage/Implementation/StorageAccessHandler.cs
=> update pep,abac,platform.models package version

src/Services/Storage/Implementation/DataRepository.cs
Syncronization with a change [implemented in Altinn.Storage](https://github.com/Altinn/altinn-storage/pull/466/files#diff-05f49aaa32950522841b925bb7f3a25441fba09c78af6153c0dbe99d5216492fR364)
- https://github.com/Altinn/app-lib-dotnet/issues/707
- https://github.com/Altinn/altinn-storage/pull/466
=> Ordered DataElements 

testdata/Profile/User/1004.json, testdata/Register/Party/510004.json, testdata/authorization/partylist/1004.json, testdata/authorization/roles/User_1004/party_510004/roles.json
=> Adding a self-identified user

src/Controllers/Storage/DataController.cs, src/LocalTest.csproj, src/Services/Storage/Implementation/DataRepository.cs
Add mappings for updating userDefinedMetadata and metadata on data element.
=> Add mappings for updating userDefinedMetadata and metadata on data element

README.md
Updated .net requirement, formating and describing workaround/solution for https://github.com/Altinn/app-localtest/issues/84
=> Updates based on recent run-through. 

src/Controllers/HomeController.cs
To enable apps to verify that the localtest version is new enough
- N/A
=> Version endpoint in HomeController

src/Controllers/Storage/InstancesController.cs, src/Helpers/Storage/AuthorizationHelper.cs, src/LocalTest.csproj, src/Services/Storage/Implementation/AuthorizationService.cs, src/Services/Storage/Implementation/StorageAccessHandler.cs
Updates `Altinn.Common.PEP` from v3 to v4. The update is following the same changes as done be renovate bot in [altinn-storage commit 1f85c8b858d0be2a9bd719bfa60cb0f5a948acf0](https://github.com/Altinn/altinn-storage/commit/1f85c8b858d0be2a9bd719bfa60cb0f5a948acf0)
The intention of this change is to upgrade `Altinn.Common.PEP` so that another change in [altinn-storage(commit 4b244640658a1b6939809167f2c14aff6eb929cd)](https://github.com/Altinn/altinn-storage/commit/4b244640658a1b6939809167f2c14aff6eb929cd) can be done.
=> Update Altinn.Common.PEP from v3 to v4

src/Views/Home/Tokens.cshtml, src/appsettings.json
Minor wording and layout tweaks to the /Tokens page.
=> Token page tweaks

docker-compose.yml, loadbalancer/templates/nginx.conf.conf, src/Configuration/LocalPlatformSettings.cs, src/Controllers/Authentication/OpenIdController.cs, src/Controllers/Authorization/DecisionController.cs, src/Controllers/Authorization/RolesController.cs, src/Controllers/HomeController.cs, src/Controllers/Storage/DataController.cs, src/Controllers/Storage/InstancesController.cs, src/Controllers/Storage/ProcessController.cs, src/Controllers/Storage/SignController.cs, src/Helpers/Storage/ClaimsPrincipalExtensions.cs, src/Helpers/Storage/ProcessHelper.cs, src/LocalTest.csproj, src/Models/TokensModel.cs, src/Services/Authentication/Implementation/AuthenticationService.cs, src/Services/Authentication/Interface/IAuthentication.cs, src/Services/Storage/Implementation/AuthorizationService.cs, src/Services/Storage/Implementation/ClaimsPrincipalProvider.cs, src/Services/Storage/Implementation/InstanceEventService.cs, src/Services/Storage/Implementation/InstanceService.cs, src/Services/Storage/Interface/IInstanceService.cs, src/Services/TestData/TestDataDiskReader.cs, src/Services/TestData/TestDataModel.cs, src/Startup.cs, src/Views/Home/Tokens.cshtml, src/appsettings.json, testdata/authorization/systems/913312465_sbs/system.json, testdata/authorization/systems/913312465_sbs/systemusers/950474084.json
Support systemusers
* Extended tokens view
* Update storage impl in regards to systemusers
* Builtin test data for systemusers
* Authorize based on systemuser testdata
-  https://github.com/Altinn/altinn-storage/issues/613
=> Support systemuser

src/Controllers/Authorization/DecisionController.cs
This change ensures that we use org and app attributes or the `urn:altinn:resource` attribute to match whatever is present in the resource attributes for the incoming authorization request. I'm not sure if this is the correct way but it works
- #151
=> Handle resource 'urn:altinn:resource' attribute containing app format for instance delegations

src/Controllers/AccessManagement/AppsInstanceDelegationController.cs
Forgot to remove this in the initial implementation
- N/A
=> Remove PAT parameter from instance delegation controller

README.md
=> Updates outdated links to docs in README

src/Services/Tenor/TenorDataReader.cs
=> Removes file name restriction for tenor data source files

testdata/authorization/partylist/1337.json
Caught by coderabbit: https://github.com/Altinn/app-lib-dotnet/pull/1446#discussion_r2293735012
- N/A
=> Consistent SSN for Sophie Salt

docker-compose.yml, podman-compose.yml
Syncs with https://github.com/Altinn/altinn-studio-charts/pull/59
=> Set timezone in chrome
